In [1]:
# mount google drive in to your Colab enviornment
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
cd /content/drive/MyDrive/ai_assignment/


/content/drive/MyDrive/ai_assignment


In [3]:
import pandas as pd
import numpy as np
car_data = pd.read_csv('./Car.csv')

In [4]:
import tensorflow as tf

In [5]:
car_data

car_ID  symboling                   CarName  ... citympg highwaympg    price
0         1          3        alfa-romero giulia  ...      21         27  13495.0
1         2          3       alfa-romero stelvio  ...      21         27  16500.0
2         3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3         4          2               audi 100 ls  ...      24         30  13950.0
4         5          2                audi 100ls  ...      18         22  17450.0
..      ...        ...                       ...  ...     ...        ...      ...
200     201         -1           volvo 145e (sw)  ...      23         28  16845.0
201     202         -1               volvo 144ea  ...      19         25  19045.0
202     203         -1               volvo 244dl  ...      18         23  21485.0
203     204         -1                 volvo 246  ...      26         27  22470.0
204     205         -1               volvo 264gl  ...      19         25  22625.0

[205 rows x 26 columns]

In [6]:
#check if there are empty cells, if there are then row and column indexes will be returned where values are empty or missing
np.where(car_data.applymap(lambda x: x ==''))

(array([], dtype=int64), array([], dtype=int64))

In [7]:
car_data.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [8]:
# drop useless column
car_data.drop(columns = ['car_ID'], inplace= True)

In [10]:

car_data['CarName'].unique()

array(['alfa-romero giulia', 'alfa-romero stelvio',
       'alfa-romero Quadrifoglio', 'audi 100 ls', 'audi 100ls',
       'audi fox', 'audi 5000', 'audi 4000', 'audi 5000s (diesel)',
       'bmw 320i', 'bmw x1', 'bmw x3', 'bmw z4', 'bmw x4', 'bmw x5',
       'chevrolet impala', 'chevrolet monte carlo', 'chevrolet vega 2300',
       'dodge rampage', 'dodge challenger se', 'dodge d200',
       'dodge monaco (sw)', 'dodge colt hardtop', 'dodge colt (sw)',
       'dodge coronet custom', 'dodge dart custom',
       'dodge coronet custom (sw)', 'honda civic', 'honda civic cvcc',
       'honda accord cvcc', 'honda accord lx', 'honda civic 1500 gl',
       'honda accord', 'honda civic 1300', 'honda prelude',
       'honda civic (auto)', 'isuzu MU-X', 'isuzu D-Max ',
       'isuzu D-Max V-Cross', 'jaguar xj', 'jaguar xf', 'jaguar xk',
       'maxda rx3', 'maxda glc deluxe', 'mazda rx2 coupe', 'mazda rx-4',
       'mazda glc deluxe', 'mazda 626', 'mazda glc', 'mazda rx-7 gs',
       'mazda glc 

In [11]:
# correct the name error in audi 100 ls
car_data.iloc[3,2] = 'audi 100ls'

In [12]:
car_data.dtypes

symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [13]:
car_data.columns

Index(['symboling', 'CarName', 'fueltype', 'aspiration', 'doornumber',
       'carbody', 'drivewheel', 'enginelocation', 'wheelbase', 'carlength',
       'carwidth', 'carheight', 'curbweight', 'enginetype', 'cylindernumber',
       'enginesize', 'fuelsystem', 'boreratio', 'stroke', 'compressionratio',
       'horsepower', 'peakrpm', 'citympg', 'highwaympg', 'price'],
      dtype='object')

In [14]:
final_car = pd.get_dummies(car_data, columns=['symboling','CarName','fueltype',	'aspiration',	'doornumber',	'carbody',	'drivewheel',	'enginelocation',	'enginetype',	'cylindernumber',	'fuelsystem'])


In [15]:
final_car.describe()

wheelbase   carlength  ...  fuelsystem_spdi  fuelsystem_spfi
count  205.000000  205.000000  ...       205.000000       205.000000
mean    98.756585  174.049268  ...         0.043902         0.004878
std      6.021776   12.337289  ...         0.205380         0.069843
min     86.600000  141.100000  ...         0.000000         0.000000
25%     94.500000  166.300000  ...         0.000000         0.000000
50%     97.000000  173.200000  ...         0.000000         0.000000
75%    102.400000  183.100000  ...         0.000000         0.000000
max    120.900000  208.100000  ...         1.000000         1.000000

[8 rows x 206 columns]

In [18]:
#for seperating 70 percent of data
np.random.seed(11111)
msk = np.random.rand(len(final_car)) < 0.70
train_total = final_car[msk]
test_total = final_car[~msk]


In [19]:
#check the length of our test and train datasets
print(len(train_total))
print(len(test_total))


136
69


In [20]:
train_total.head(10)

wheelbase  carlength  ...  fuelsystem_spdi  fuelsystem_spfi
1        88.6      168.8  ...                0                0
2        94.5      171.2  ...                0                0
3        99.8      176.6  ...                0                0
4        99.4      176.6  ...                0                0
5        99.8      177.3  ...                0                0
6       105.8      192.7  ...                0                0
7       105.8      192.7  ...                0                0
8       105.8      192.7  ...                0                0
9        99.5      178.2  ...                0                0
11      101.2      176.8  ...                0                0

[10 rows x 206 columns]

In [21]:
train_total.describe()

wheelbase   carlength  ...  fuelsystem_spdi  fuelsystem_spfi
count  136.000000  136.000000  ...       136.000000       136.000000
mean    98.589706  173.358824  ...         0.036765         0.007353
std      5.956935   12.299626  ...         0.188879         0.085749
min     86.600000  144.600000  ...         0.000000         0.000000
25%     94.500000  166.150000  ...         0.000000         0.000000
50%     96.500000  172.000000  ...         0.000000         0.000000
75%    102.400000  178.950000  ...         0.000000         0.000000
max    115.600000  202.600000  ...         1.000000         1.000000

[8 rows x 206 columns]

In [22]:
print(train_total.dtypes)

wheelbase          float64
carlength          float64
carwidth           float64
carheight          float64
curbweight           int64
                    ...   
fuelsystem_idi       uint8
fuelsystem_mfi       uint8
fuelsystem_mpfi      uint8
fuelsystem_spdi      uint8
fuelsystem_spfi      uint8
Length: 206, dtype: object


In [23]:
train_label = train_total.loc[:,'price']
test_label = test_total.loc[:,'price']

In [25]:
train_label

1      16500.0
2      16500.0
3      13950.0
4      17450.0
5      15250.0
        ...   
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 136, dtype: float64

In [26]:
test_data  = test_total.drop(columns = ['price'])
train_data = train_total.drop(columns = ['price'])

In [27]:
train_data.shape

(136, 205)

In [28]:
train_data

wheelbase  carlength  ...  fuelsystem_spdi  fuelsystem_spfi
1         88.6      168.8  ...                0                0
2         94.5      171.2  ...                0                0
3         99.8      176.6  ...                0                0
4         99.4      176.6  ...                0                0
5         99.8      177.3  ...                0                0
..         ...        ...  ...              ...              ...
200      109.1      188.8  ...                0                0
201      109.1      188.8  ...                0                0
202      109.1      188.8  ...                0                0
203      109.1      188.8  ...                0                0
204      109.1      188.8  ...                0                0

[136 rows x 205 columns]

In [30]:
#Normalization
mean = train_data.iloc[:,0:13].mean(axis=0)
train_data.iloc[:,0:13] -= mean
std = train_data.iloc[:,0:13].std(axis=0)
train_data.iloc[:,0:13] /= std
test_data.iloc[:,0:13] -= mean
test_data.iloc[:,0:13] /= std



In [ ]:
# x = (y - z)/ std

In [31]:
mean_label = train_label.mean()
train_label -= mean_label
std_label = train_label.std()
train_label /= std_label
test_label -= mean_label
test_label /= std_label


In [32]:
print(mean_label)

13356.475492647058


In [33]:
test_label

0      0.016675
10     0.369972
13     0.932719
14     1.349212
15     2.094927
         ...   
192    0.058806
193   -0.128376
194   -0.050133
196    0.316405
198    0.609515
Name: price, Length: 69, dtype: float64

In [34]:
train_data

wheelbase  carlength  ...  fuelsystem_spdi  fuelsystem_spfi
1    -1.676987  -0.370647  ...                0                0
2    -0.686545  -0.175519  ...                0                0
3     0.203174   0.263518  ...                0                0
4     0.136025   0.263518  ...                0                0
5     0.203174   0.320431  ...                0                0
..         ...        ...  ...              ...              ...
200   1.764379   1.255418  ...                0                0
201   1.764379   1.255418  ...                0                0
202   1.764379   1.255418  ...                0                0
203   1.764379   1.255418  ...                0                0
204   1.764379   1.255418  ...                0                0

[136 rows x 205 columns]

In [39]:
#data converted to array
test = np.array(test_data.iloc[:])
train = np.array(train_data.iloc[:])
test_l= np.array(test_label.astype('float32'))
train_l= np.array(train_label.astype('float32'))

In [41]:
train.shape

(136, 205)

In [42]:
#Model
from keras import models
from keras import layers
def build_model(act):
  model = models.Sequential()
  model.add(layers.Dense(10, activation= act,input_shape=(train.shape[1],)))
  model.add(layers.Dense(8, activation= act))
  model.add(layers.Dense(6, activation= act))
  model.add(layers.Dense(1))
  model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
  return model

In [43]:
build_model('relu').summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                2060      
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 54        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7         
Total params: 2,209
Trainable params: 2,209
Non-trainable params: 0
_________________________________________________________________


In [44]:
build_model('tanh').summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 10)                2060      
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_6 (Dense)              (None, 6)                 54        
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 7         
Total params: 2,209
Trainable params: 2,209
Non-trainable params: 0
_________________________________________________________________


In [45]:
# Regularized model
from keras import regularizers
def build_model_regular(act):
  model = models.Sequential()
  model.add(layers.Dense(10, activation= act,kernel_regularizer= regularizers.l1_l2(l1=0.001, l2=0.001),input_shape=(train.shape[1],)))
  model.add(layers.Dense(8, activation= act,kernel_regularizer= regularizers.l1_l2(l1=0.001, l2=0.001)))
  model.add(layers.Dense(6, activation= act,kernel_regularizer= regularizers.l1_l2(l1=0.001, l2=0.001)))
  model.add(layers.Dense(1))
  model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
  return model

In [46]:
build_model_regular('tanh').summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 10)                2060      
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_10 (Dense)             (None, 6)                 54        
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 7         
Total params: 2,209
Trainable params: 2,209
Non-trainable params: 0
_________________________________________________________________


In [47]:
# dropout model
from keras import regularizers
def build_model_drop(act):
  model = models.Sequential()
  model.add(layers.Dense(10, activation= act,input_shape=(train.shape[1],)))
  model.add(layers.Dropout(0.5))
  model.add(layers.Dense(8, activation= act))
  model.add(layers.Dropout(0.5))
  model.add(layers.Dense(6, activation= act))
  model.add(layers.Dropout(0.5))
  model.add(layers.Dense(1))
  model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
  return model

In [48]:
#k fold validation with relu
# 141/4
import numpy as np
k =  4
num_val_samples = len(train) // k
num_epochs = 100
all_scores_relu = []
for i in range(k):
  print('processing fold #', i)
  val_data = train[i * num_val_samples: (i + 1) * num_val_samples]
  val_targets = train_l[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate([train[:i * num_val_samples],train[(i + 1) * num_val_samples:]],  axis=0)
  # print(partial_train_data)
  partial_train_targets = np.concatenate([train_l[:i * num_val_samples],train_l[(i + 1) * num_val_samples:]],axis=0)
  model = build_model('relu')
  model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
  all_scores_relu.append(val_mae)


processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3


In [49]:
# 141/4
#k fold validation with tanh
import numpy as np
k =  4
num_val_samples = len(train) // k
num_epochs = 100
all_scores_tanh = []
for i in range(k):
  print('processing fold #', i)
  val_data = train[i * num_val_samples: (i + 1) * num_val_samples]
  val_targets = train_l[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate([train[:i * num_val_samples],train[(i + 1) * num_val_samples:]],  axis=0)
  # print(partial_train_data)
  partial_train_targets = np.concatenate([train_l[:i * num_val_samples],train_l[(i + 1) * num_val_samples:]],axis=0)
  model = build_model('tanh')
  model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
  all_scores_tanh.append(val_mae)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3


In [50]:
#k-fold validtion with regularization
import numpy as np
k =  4
num_val_samples = len(train) // k
num_epochs = 100
all_scores_regular = []
for i in range(k):
  print('processing fold #', i)
  val_data = train[i * num_val_samples: (i + 1) * num_val_samples]
  val_targets = train_l[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate([train[:i * num_val_samples],train[(i + 1) * num_val_samples:]],  axis=0)
  # print(partial_train_data)
  partial_train_targets = np.concatenate([train_l[:i * num_val_samples],train_l[(i + 1) * num_val_samples:]],axis=0)
  model = build_model_regular('relu')
  model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
  all_scores_regular.append(val_mae)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3


In [52]:
#k-fold validtion with dropout
import numpy as np
k =  4
num_val_samples = len(train) // k
num_epochs = 100
all_scores_drop = []
for i in range(k):
  
  print('processing fold #', i)
  
  val_data = train[i * num_val_samples: (i + 1) * num_val_samples]

  val_targets = train_l[i * num_val_samples: (i + 1) * num_val_samples]
  
  partial_train_data = np.concatenate([train[:i * num_val_samples],train[(i + 1) * num_val_samples:]],  axis=0)
  
  print(partial_train_data)
  
  partial_train_targets = np.concatenate([train_l[:i * num_val_samples],train_l[(i + 1) * num_val_samples:]],axis=0)
  
  model = build_model_drop('relu')
  
  model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
  
  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
  
  all_scores_drop.append(val_mae)

processing fold # 0
[[ 0.57249138  1.49119785  2.13964666 ...  1.          0.
   0.        ]
 [-0.92156547 -1.15928915 -0.74995528 ...  0.          0.
   0.        ]
 [-0.92156547 -1.15928915 -0.74995528 ...  0.          0.
   0.        ]
 ...
 [ 1.76437942  1.25541833  1.37209614 ...  1.          0.
   0.        ]
 [ 1.76437942  1.25541833  1.37209614 ...  0.          0.
   0.        ]
 [ 1.76437942  1.25541833  1.37209614 ...  1.          0.
   0.        ]]
processing fold # 1
[[-1.67698747 -0.37064732 -0.79510531 ...  1.          0.
   0.        ]
 [-0.68654529 -0.17551944 -0.16300489 ...  1.          0.
   0.        ]
 [ 0.20317396  0.26351829  0.15304532 ...  1.          0.
   0.        ]
 ...
 [ 1.76437942  1.25541833  1.37209614 ...  1.          0.
   0.        ]
 [ 1.76437942  1.25541833  1.37209614 ...  0.          0.
   0.        ]
 [ 1.76437942  1.25541833  1.37209614 ...  1.          0.
   0.        ]]
processing fold # 2
[[-1.67698747 -0.37064732 -0.79510531 ...  1.       

In [53]:
all_scores_relu

[0.32939282059669495,
 0.24984735250473022,
 0.35248932242393494,
 0.3652627468109131]

In [54]:
all_scores_tanh

[0.3019961714744568,
 0.29715627431869507,
 0.4751357436180115,
 0.5424004793167114]

In [55]:
all_scores_regular

[0.36824485659599304,
 0.1914176344871521,
 0.39493250846862793,
 0.33377113938331604]

In [56]:
all_scores_drop

[0.7519665360450745, 0.629912257194519, 0.6267066597938538, 0.3689258396625519]

In [57]:
model_tanh = build_model('tanh')
model_tanh.fit(train, train_l,epochs= 80, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_tanh.evaluate(test, test_l)

3/3 [==============================] - 0s 5ms/step - loss: 0.0854 - mae: 0.2204


In [59]:
model_relu = build_model('relu')
model_relu.fit(train, train_l,epochs= 80, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_relu.evaluate(test, test_l)

3/3 [==============================] - 0s 4ms/step - loss: 0.1069 - mae: 0.2363


In [60]:
model_regular = build_model_regular('relu')
model_regular.fit(train, train_l,epochs= 80, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_relu.evaluate(test, test_l)

3/3 [==============================] - 0s 5ms/step - loss: 0.1069 - mae: 0.2363


In [61]:
model_drop = build_model_drop('relu')
model_drop.fit(train, train_l,epochs= 80, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_relu.evaluate(test, test_l)

3/3 [==============================] - 0s 4ms/step - loss: 0.1069 - mae: 0.2363


In [63]:
x_tanh = model_tanh.predict(test[5].reshape(1,test.shape[1]))
x_tanh

array([[-1.2477875]], dtype=float32)

In [64]:
x_tanh * std_label + mean_label

array([[2990.5312]], dtype=float32)

In [65]:
x_relu = model_relu.predict(test[5].reshape(1,test.shape[1]))

In [67]:
x_relu * std_label + mean_label

array([[4819.6064]], dtype=float32)

In [68]:
x_regular = model_regular.predict(test[5].reshape(1,test.shape[1]))
x_regular * std_label + mean_label

array([[4839.534]], dtype=float32)

In [69]:
x_drop = model_drop.predict(test[5].reshape(1,test.shape[1]))
x_drop * std_label + mean_label

array([[10092.789]], dtype=float32)

In [70]:
test_l[5]* std_label + mean_label

5151.000089577397